### ISSUE TITLE
[Tatsuyaさん質問]Mnemonicの表示タイミングについて

### ISSUE THREAD

**Issue by tatsuya0505** [extropiescom/bladeX#6]
Mnemonicの最初の表示はどのAPIが呼ばれた時に表示されるのか？

**Comment by tatsuya0505** [comment]
Thank you.
Is generateSeed_GetMnes called only once?

**Comment by cooltiger** [comment]
问题的中文翻译：
调用Mnemonic的初始显示时，是通过调用哪个API来显示的？

**Comment by eshangui** [comment]
Yes, once the mnemonics are successfully checked, the bladeX will change its state to INITIALIZED (a inner state in hardware) so that the following call of generateSeed_GetMnes will result in error PAEW_RET_DEV_STATE_INVALID, if you want to generate a new seed again, you should call PAEW_Format to  format the bladeX first.

**Comment by tatsuya0505** [comment]
I see.
Thank you.
